name: pancancer-evaluation
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel=5.3.4
  - ipython=7.16.1
  - jupyter_core=4.6.3
  - matplotlib=3.3.0
  - matplotlib-venn=0.11.5
  - numpy=1.16.5
  - pandas=0.24.2
  - pytest=5.4.3
  - python=3.6.9
  - scikit-learn=0.21.2
  - seaborn=0.10.1
  - statsmodels=0.11.1
  - tqdm=4.48.2

