name: pc-eval
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel=6.9.1
  - ipython=8.4.0
  - jupyter_core=4.10.0
  - matplotlib=3.5.1
  - matplotlib-venn=0.11.5
  - numpy=1.19.2
  - pandas=1.4.3
  - papermill=2.3.4
  - pytest=7.1.2
  - python=3.9.15
  - scikit-learn=1.1.1
  - seaborn=0.11.2
  - tqdm=4.64.0
  - umap-learn=0.4.2
  - upsetplot=0.6.1

